// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qkq1GYJeSisdsoHAunA7GS
// Component: LUt3jcnr2mbD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: tSPm0LoBpBYbm/component
import Button from "../../Button"; // plasmic-import: FHsN5oHAGgn/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_copy_of_chat_box_sg.module.css"; // plasmic-import: qkq1GYJeSisdsoHAunA7GS/projectcss
import sty from "./PlasmicPage2.module.css"; // plasmic-import: LUt3jcnr2mbD/css

export const PlasmicPage2__VariantProps = new Array();

export const PlasmicPage2__ArgProps = new Array();

function PlasmicPage2__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              sty.root
            )}
          >
            <TextInput
              data-plasmic-name={"textInput"}
              data-plasmic-override={overrides.textInput}
              className={classNames("__wab_instance", sty.textInput)}
            />

            <Button
              data-plasmic-name={"send"}
              data-plasmic-override={overrides.send}
              className={classNames("__wab_instance", sty.send)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mGzVb
                )}
              >
                {"Send"}
              </div>
            </Button>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__o80Fu
              )}
            >
              {"Hi !!"}
            </div>
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput", "textbox", "send"],
  textInput: ["textInput", "textbox"],
  send: ["send"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPage2__ArgProps,
      internalVariantPropNames: PlasmicPage2__VariantProps
    });

    return PlasmicPage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPage2";
  } else {
    func.displayName = `PlasmicPage2.${nodeName}`;
  }
  return func;
}

export const PlasmicPage2 = Object.assign(
  // Top-level PlasmicPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    send: makeNodeComponent("send"),
    // Metadata about props expected for PlasmicPage2
    internalVariantProps: PlasmicPage2__VariantProps,
    internalArgProps: PlasmicPage2__ArgProps
  }
);

export default PlasmicPage2;
/* prettier-ignore-end */
